// Offline sprite bundle.
// The 151 Gen 1 pixel sprites come from the `pokesprite-images` npm package and are
// inlined into the build as base64 data URIs (`?inline`). vite-plugin-singlefile then
// embeds them in dist/index.html, so the game needs no network access at all.

const files = import.meta.glob(
  [
    '/node_modules/pokesprite-images/pokemon-gen8/regular/bulbasaur.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/ivysaur.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/venusaur.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/charmander.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/charmeleon.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/charizard.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/squirtle.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/wartortle.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/blastoise.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/caterpie.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/metapod.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/butterfree.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/weedle.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/kakuna.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/beedrill.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/pidgey.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/pidgeotto.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/pidgeot.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/rattata.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/raticate.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/spearow.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/fearow.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/ekans.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/arbok.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/pikachu.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/raichu.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/sandshrew.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/sandslash.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/nidoran-f.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/nidorina.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/nidoqueen.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/nidoran-m.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/nidorino.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/nidoking.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/clefairy.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/clefable.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/vulpix.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/ninetales.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/jigglypuff.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/wigglytuff.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/zubat.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/golbat.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/oddish.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/gloom.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/vileplume.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/paras.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/parasect.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/venonat.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/venomoth.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/diglett.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/dugtrio.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/meowth.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/persian.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/psyduck.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/golduck.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/mankey.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/primeape.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/growlithe.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/arcanine.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/poliwag.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/poliwhirl.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/poliwrath.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/abra.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/kadabra.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/alakazam.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/machop.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/machoke.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/machamp.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/bellsprout.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/weepinbell.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/victreebel.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/tentacool.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/tentacruel.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/geodude.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/graveler.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/golem.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/ponyta.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/rapidash.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/slowpoke.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/slowbro.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/magnemite.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/magneton.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/farfetchd.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/doduo.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/dodrio.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/seel.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/dewgong.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/grimer.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/muk.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/shellder.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/cloyster.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/gastly.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/haunter.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/gengar.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/onix.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/drowzee.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/hypno.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/krabby.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/kingler.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/voltorb.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/electrode.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/exeggcute.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/exeggutor.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/cubone.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/marowak.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/hitmonlee.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/hitmonchan.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/lickitung.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/koffing.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/weezing.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/rhyhorn.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/rhydon.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/chansey.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/tangela.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/kangaskhan.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/horsea.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/seadra.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/goldeen.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/seaking.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/staryu.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/starmie.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/mr-mime.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/scyther.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/jynx.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/electabuzz.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/magmar.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/pinsir.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/tauros.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/magikarp.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/gyarados.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/lapras.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/ditto.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/eevee.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/vaporeon.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/jolteon.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/flareon.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/porygon.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/omanyte.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/omastar.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/kabuto.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/kabutops.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/aerodactyl.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/snorlax.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/articuno.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/zapdos.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/moltres.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/dratini.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/dragonair.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/dragonite.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/mewtwo.png',
    '/node_modules/pokesprite-images/pokemon-gen8/regular/mew.png',
  ],
  { eager: true, query: '?inline', import: 'default' },
) as Record<string, string>;

/** Turns a display name ("Nidoran♀", "Mr. Mime", "Farfetch'd") into the sprite file slug. */
function slugOf(name: string): string {
  return name
    .toLowerCase()
    .replace('♀', '-f')
    .replace('♂', '-m')
    .replace(/[.']/g, '')
    .replace(/\s+/g, '-');
}

const BY_SLUG = new Map<string, string>();
for (const [path, url] of Object.entries(files)) {
  BY_SLUG.set(path.slice(path.lastIndexOf('/') + 1, -'.png'.length), url);
}

/** Returns a data: URI for the Pokémon's pixel sprite, or '' if it is missing. */
export function spriteByName(name: string): string {
  return BY_SLUG.get(slugOf(name)) ?? '';
}
